from oppia.badges.all_activities import BadgeAllActivities
from oppia.badges.final_quiz import BadgeFinalQuiz
from oppia.badges.all_quizzes import BadgeAllQuizzes
from oppia.badges.all_quizzes_plus_percent import BadgeAllQuizzesPlusPercent
from oppia.badges.badge_activity_completion_percent import BadgeActivityCompletionPercent
